from youtube_transcript_api import YouTubeTranscriptApi
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
import re
from isodate import parse_duration
import pandas as pd
import datetime
import time
import random

# Criando dicionário para frequência de palavras
frequencia_palavras = {
"achievements":0,
"adventure":0,
"afk":0,
"aggro":0,
"airdrop":0,
"alfa":0,
"anti-air":0,
"anti-aliasing":0,
"aoe":0,
"arcade":0,
"assist":0,
"attachment":0,
"avatar":0,
"bait":0,
"ban":0,
"based":0,
"beat'em up":0,
"beta":0,
"bonfire":0,
"bonfires":0,
"boom":0,
"booma":0,
"boomada":0,
"boomadas":0,
"boomado":0,
"boomados":0,
"boomam":0,
"boomamos":0,
"boomando":0,
"boomei":0,
"boomo":0,
"boomou":0,
"boss":0,
"bot":0,
"box":0,
"buff":0,
"buffa":0,
"buffada":0,
"buffado":0,
"buffam":0,
"buffando":0,
"buffar":0,
"buffei":0,
"buffer":0,
"buffera":0,
"bufferada":0,
"bufferadas":0,
"bufferado":0,
"bufferados":0,
"bufferam":0,
"bufferamos":0,
"bufferando":0,
"bufferei":0,
"buffero":0,
"bufferou":0,
"buffou":0,
"buffs":0,
"bug":0,
"bugadaço":0,
"bugs":0,
"build":0,
"buildada":0,
"burnout":0,
"caixista":0,
"call":0,
"camper":0,
"camperar":0,
"cancel":0,
"cancels":0,
"cap":0,
"capa":0,
"capada":0,
"capadas":0,
"capado":0,
"capados":0,
"capam":0,
"capamos":0,
"capando":0,
"capei":0,
"capo":0,
"capou":0,
"carry forward":0,
"caster":0,
"challenge":0,
"challenges":0,
"char":0,
"charge":0,
"chat":0,
"cheat":0,
"checkpoint":0,
"co-op":0,
"combo":0,
"comeback":0,
"cooldown":0,
"counter":0,
"counterar":0,
"craft":0,
"crafta":0,
"craftada":0,
"craftado":0,
"craftam":0,
"craftando":0,
"craftar":0,
"craftei":0,
"crafting":0,
"craftou":0,
"crate":0,
"critical":0,
"crossup":0,
"cutscene":0,
"debuff":0,
"deck":0,
"decks":0,
"delay":0,
"demo":0,
"dlc":0,
"dps":0,
"drift":0,
"drop":0,
"dropa":0,
"dropada":0,
"dropado":0,
"dropam":0,
"dropando":0,
"dropar":0,
"dropei":0,
"dropou":0,
"dropshot":0,
"drush":0,
"dungeon":0,
"dungeons":0,
"dupe":0,
"easteregg":0,
"eastereggs":0,
"easy":0,
"elo":0,
"engine":0,
"exp":0,
"exploit":0,
"fangame":0,
"farm":0,
"farma":0,
"farmada":0,
"farmadas":0,
"farmado":0,
"farmados":0,
"farmam":0,
"farmamos":0,
"farmando":0,
"farmar":0,
"farmei":0,
"farming":0,
"farmo":0,
"farmou":0,
"fast castle":0,
"fast imp":0,
"fatalities":0,
"fatality":0,
"feature":0,
"features":0,
"fgc":0,
"fight":0,
"flop":0,
"flopa":0,
"flopada":0,
"flopado":0,
"flopam":0,
"flopando":0,
"flopou":0,
"flush":0,
"fov":0,
"fps":0,
"fuzzy jab":0,
"game":0,
"gameplay":0,
"gang":0,
"ganga":0,
"gangada":0,
"gangadas":0,
"gangado":0,
"gangados":0,
"gangam":0,
"gangamos":0,
"gangando":0,
"gangei":0,
"gango":0,
"gangou":0,
"gank":0,
"ganka":0,
"gankada":0,
"gankado":0,
"gankam":0,
"gankando":0,
"gankar":0,
"gankei":0,
"gankou":0,
"gap":0,
"gg":0,
"glitch":0,
"glitching":0,
"grab":0,
"grabs":0,
"grind":0,
"grinda":0,
"grindam":0,
"grindando":0,
"grindar":0,
"grindei":0,
"grindes":0,
"grindou":0,
"guild":0,
"hack":0,
"hack'n slash":0,
"hacker":0,
"harass":0,
"hard":0,
"hardcore":0,
"headshot":0,
"heal":0,
"heallar":0,
"healler":0,
"hill":0,
"hitbox":0,
"hits":0,
"hp":0,
"hud":0,
"hurtbox":0,
"hypa":0,
"hypada":0,
"hypado":0,
"hypam":0,
"hypando":0,
"hype":0,
"hypou":0,
"i-frame":0,
"i-frames":0,
"indie":0,
"indies":0,
"joypad":0,
"joystick":0,
"juggle":0,
"jumpshot":0,
"kick":0,
"kicka":0,
"kickada":0,
"kickado":0,
"kickam":0,
"kickando":0,
"kickar":0,
"kickei":0,
"kickou":0,
"kill":0,
"kina":0,
"kinas":0,
"lag":0,
"laga":0,
"lagada":0,
"lagadaço":0,
"lagado":0,
"lagam":0,
"lagando":0,
"lagar":0,
"lagei":0,
"lagou":0,
"leakers":0,
"level":0,
"like":0,
"live":0,
"lobby":0,
"lol":0,
"loot":0,
"lootear":0,
"looteia":0,
"looteiam":0,
"looter":0,
"lootiada":0,
"lootiado":0,
"lootiando":0,
"lootiei":0,
"lootiou":0,
"lore":0,
"lura":0,
"lurando":0,
"lurar":0,
"lure":0,
"lurou":0,
"lv":0,
"macro":0,
"main":0,
"match":0,
"matchmaking":0,
"medium":0,
"melee":0,
"meta":0,
"metroidvania":0,
"metroidvanias":0,
"micro":0,
"microtransação":0,
"miniboss":0,
"mmo":0,
"mmorpg":0,
"mob":0,
"mobile":0,
"mobs":0,
"mod":0,
"mods":0,
"mosho":0,
"multiplataforma":0,
"multiplayer":0,
"muzzle":0,
"negative edge":0,
"nerf":0,
"nerfa":0,
"nerfada":0,
"nerfado":0,
"nerfam":0,
"nerfando":0,
"nerfar":0,
"nerfei":0,
"nerfou":0,
"nerfs":0,
"newbie":0,
"nick":0,
"noob":0,
"npc":0,
"npcs":0,
"oki":0,
"okizeme":0,
"op":0,
"option":0,
"options":0,
"parry":0,
"pass":0,
"patch":0,
"perfect":0,
"perk":0,
"perks":0,
"permadeath":0,
"ping":0,
"platina":0,
"platinada":0,
"platinado":0,
"platinam":0,
"platinar":0,
"platinei":0,
"platinou":0,
"play":0,
"player":0,
"point":0,
"points":0,
"poke":0,
"pokes":0,
"port":0,
"post":0,
"pov":0,
"punish":0,
"punishes":0,
"pushback":0,
"puzzle":0,
"pve":0,
"pvp":0,
"quebrado":0,
"quest":0,
"quickscope":0,
"quit":0,
"quita":0,
"quitado":0,
"quitam":0,
"quitando":0,
"quitar":0,
"quitei":0,
"quitou":0,
"rage":0,
"ragequit":0,
"raid":0,
"raida":0,
"raidada":0,
"raidadas":0,
"raidado":0,
"raidados":0,
"raidam":0,
"raidamos":0,
"raidando":0,
"raidei":0,
"raido":0,
"raidou":0,
"reboot":0,
"record":0,
"remake":0,
"remaster":0,
"respawn":0,
"respawna":0,
"respawnam":0,
"respawnando":0,
"respawnar":0,
"respawnei":0,
"respawnou":0,
"reversal":0,
"reversals":0,
"roguelike":0,
"roubado":0,
"round":0,
"rounds":0,
"rpg":0,
"rts":0,
"rush":0,
"rusha":0,
"rushada":0,
"rushado":0,
"rusham":0,
"rushando":0,
"rushar":0,
"rushdown":0,
"rushei":0,
"rushou":0,
"safe":0,
"sandbox":0,
"save":0,
"savepoint":0,
"scout":0,
"scouta":0,
"scoutada":0,
"scoutadas":0,
"scoutado":0,
"scoutados":0,
"scoutam":0,
"scoutamos":0,
"scoutando":0,
"scoutei":0,
"scouto":0,
"scoutou":0,
"season":0,
"setup":0,
"setups":0,
"shooter":0,
"shoto":0,
"sidequest":0,
"skill":0,
"skin":0,
"skins":0,
"skirm":0,
"skirms":0,
"slida":0,
"slidam":0,
"slidando":0,
"slidar":0,
"slide":0,
"slidei":0,
"slidou":0,
"smurf":0,
"snaipa":0,
"snaipam":0,
"snaipando":0,
"snaipar":0,
"snaipe":0,
"snaipei":0,
"snaipou":0,
"sonista":0,
"soulslike":0,
"soulslikes":0,
"spawn":0,
"spawna":0,
"spawnado":0,
"spawnam":0,
"spawnar":0,
"spawnei":0,
"spawnou":0,
"speedrun":0,
"squad":0,
"state":0,
"stats":0,
"stealth":0,
"streak":0,
"stun":0,
"stunna":0,
"stunnada":0,
"stunnam":0,
"stunnando":0,
"stunnar":0,
"stunnei":0,
"stunner":0,
"stunnou":0,
"survival":0,
"survivals":0,
"tank":0,
"tanka":0,
"tankado":0,
"tankam":0,
"tankando":0,
"tankar":0,
"tankei":0,
"tankou":0,
"tc":0,
"tcs":0,
"throw":0,
"throws":0,
"tier":0,
"tilt":0,
"tilta":0,
"tiltada":0,
"tiltado":0,
"tiltam":0,
"tiltar":0,
"tiltou":0,
"town center":0,
"town centers":0,
"trade":0,
"trader":0,
"troll":0,
"trolla":0,
"trollada":0,
"trollado":0,
"trollam":0,
"trollando":0,
"trollar":0,
"trollei":0,
"upa":0,
"upada":0,
"upado":0,
"upam":0,
"upando":0,
"upar":0,
"upei":0,
"upgrade":0,
"upou":0,
"user":0,
"username":0,
"vil":0,
"vils":0,
"vortex":0,
"wall carry":0,
"wave":0,
"whiff":0,
"whiffa":0,
"whiffada":0,
"whiffadas":0,
"whiffado":0,
"whiffados":0,
"whiffam":0,
"whiffamos":0,
"whiffando":0,
"whiffei":0,
"whiffo":0,
"whiffou":0,
"xp":0,
"zera":0,
"zerada":0,
"zeradas":0,
"zerado":0,
"zerados":0,
"zeram":0,
"zeramos":0,
"zerando":0,
"zerar":0,
"zerei":0,
"zerou":0,
"zonear":0,
"zoner":0
}

# Configurar autenticação com o arquivo secrets.json
scopes = [
    "https://www.googleapis.com/auth/youtube.readonly",
    "https://www.googleapis.com/auth/youtube.force-ssl"
]
flow = InstalledAppFlow.from_client_secrets_file('secrets2.json', scopes)
credentials = flow.run_local_server(port=0)  # Autenticação local
youtube = build('youtube', 'v3', credentials=credentials)

# ID da playlist (encontrado na URL da playlist)
playlist_id = 'PL8L2P-Aqa4PT2KklI-1zIxQGLBL2K_zPT'

# Requisição para listar vídeos da playlist
response = youtube.playlistItems().list(
    part='contentDetails,snippet',
    playlistId=playlist_id,
    maxResults=50  # Máximo de vídeos por requisição
).execute()

# Extrair IDs dos vídeos
videos = response['items']
ids_videos = [video['contentDetails']['videoId'] for video in videos]

# Transformar IDs em texto separado por vírgulas
ids_texto = ','.join(ids_videos)

# Requisição para obter estatísticas dos vídeos
response_videos = youtube.videos().list(
    part='contentDetails,statistics,snippet',
    id=ids_texto
).execute()

# Monta arquivo para gravar caso não exista
arquivo_saida="resultados.xlsx"

try:
    df = pd.read_excel(arquivo_saida)
except FileNotFoundError:
    # adiciona cabeçalho se não tiver
    array_cabecalho = list(frequencia_palavras.keys())
    array_cabecalho.append('url')
    array_cabecalho.append('título')
    array_cabecalho.append('canal')
    array_cabecalho.append('views')
    array_cabecalho.append('número de likes')
    array_cabecalho.append('número de comentários')
    array_cabecalho.append('data de publicação')
    array_cabecalho.append('duração em segundos')
    array_cabecalho.append('total de palavras')
    array_cabecalho.append('total de palavras gamers')
    df_final = pd.DataFrame(array_cabecalho).transpose()
    df_final.to_excel(arquivo_saida, index=False, engine='openpyxl')

indiceVideo = 1
for video in response_videos['items']:
    # Adiciona um intervalo entre as requisições
    time.sleep(random.randint(3, 10))

    # Formatar a data de publicação
    data = video['snippet']['publishedAt'].split('T')[0]
    data = datetime.datetime.strptime(data, "%Y-%m-%d").date()
    data_formatada = data.strftime("%d/%m/%Y")

    # Obter dados desejados do vídeo
    metadata = {
        'url': "https://www.youtube.com/watch?v=" + video['id'],
        'titulo': video['snippet']['title'],
        'canal':  video['snippet']['channelTitle'],
        'views': video['statistics']['viewCount'],
        'likes': video['statistics']['likeCount'],
        'comentarios': video['statistics']['commentCount'],
        'data_publicacao': data_formatada,
        'duracao_segundos': int(parse_duration(video['contentDetails']['duration']).total_seconds())
    }

    # Baixar as legendas
    transcript = YouTubeTranscriptApi().list(video_id=video['id']).find_transcript(language_codes=['pt']).fetch()
    texto_completo = ""

    for i in range(len(transcript)):
        texto_completo += transcript[i].text + " "

    # Procurar as palavras desejadas
    for item in frequencia_palavras:
        frequencia_palavras[item] = len(re.findall(r'\b' + re.escape(item) + r'\b', texto_completo, re.IGNORECASE))

    # Preparando dados para gravar
    resultados = {"frequencia": frequencia_palavras, "transcricao": texto_completo, "metadados": metadata}
    transcricao_formatada = re.sub(r'\[\s*__\s*\]', '[__]', resultados['transcricao'])
    transcricao_formatada = re.sub(r'>>', '', transcricao_formatada)
    transcricao_formatada = re.sub(r'  ', '', transcricao_formatada)
    total_palavras = len(transcricao_formatada.split(" "))
    total_palavras_gamers = sum(resultados['frequencia'].values())

    # Gravando os dados
    array_dados = []
    for item in resultados['frequencia']:
        array_dados.append(resultados['frequencia'][item])

    for item in resultados['metadados'].values():
        array_dados.append(item)
    array_dados.append(total_palavras)
    array_dados.append(total_palavras_gamers)

    df = pd.DataFrame(array_dados)

    df_existente = pd.read_excel(arquivo_saida)
    df_final = pd.concat([df_existente, df.transpose()], ignore_index=True)

    df_final.to_excel(arquivo_saida, index=False, engine='openpyxl')
    print(f"Resultados do vídeo {indiceVideo} salvos em {arquivo_saida}")
    indiceVideo += 1

